-----BEGIN PRIVATE KEY-----
MIGTAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBHkwdwIBAQQgQDJk6CIS56l4PFVP
Fw5OoUQjQUVrcmcy+RtRTZKvMGKgCgYIKoZIzj0DAQehRANCAAQwZ3W2MTQhR1se
PB/f6fIrMqpSl5yoF3AnSlZEk2PXjy6FhPSbgswdk9rwwscZFTaIgdccPUrHw2t/
24+qMZln
-----END PRIVATE KEY-----